#!/home/david/ansible/myansible/bin/ansible-playbook

- name: AltSchool Docker Project
  hosts: aws_ec2
  become: true
  become_user: root
  vars:
    path: "/LaraDock"

  tasks:
    - block:
      - name: Update Packages
        command: "{{ item }}"
        with_items:
          - apt update -y 
          - apt upgrade -y

      - name: "Create Project Folder"
        ansible.builtin.file:
          path: "{{ path }}"
          state: directory
          mode: "0755"

      - name: Install Docker on Server
        command: "{{ item }}"
        with_items:
          - apt  install docker.io 
          - apt  install docker-compose
          - docker -v
        register: dockerInstallation
      - debug: var=dockerInstallation

      - name: "Clone Project Folder and Execute Docker Commands"
        command: "{{ item }}"
        with_items:
          - chdir="{{ path }}" git clone https://github.com/DavidHODs/LaraDock.git
          - chdir="{{ path }}" docker build build -t laraimage:latest .
          - chdir="{{ path }}" docker-compose -f docker-compose.yml up