#!/home/david/ansible/myansible/bin/ansible-playbook

- name: AltSchool Docker Project
  hosts: aws_ec2
  become: true
  become_user: root
  vars:
    path: "/LaraDock"


  tasks:
    - block:
      - name: Update Packages
        command: "{{ item }}"
        with_items:
          - apt update -y 
          - apt upgrade -y

      - name: Install Docker Instalation Script
        ansible.buitlin.get_url:
          url: -fsSL https://get.docker.com -o get-docker.sh &&

      - name: Execute Downloaded Docker Installation Script
        command: sh ./get-docker.sh --dry-run

      - name: "Create Project Folder"
        ansible.builtin.file:
          path: "{{ path }}"
          state: directory
          mode: "0755"

      - name: "Clone Project Folder and Execute Docker Commands"
        command: "{{ item }}"
        with_items:
          - chdir="{{ path }}" git clone https://github.com/DavidHODs/LaraDock.git
          - chdir="{{ path }}" docker build build -t laraimage:latest .
          - chdir="{{ path }}" docker-compose -f docker-compose.yml up